---
- name: Getting ready to install the SCAP packages
  hosts: all
  become: yes
  gather_facts: no
  
  tasks:
  
  - name: Making sure the packages we are need are installed.
    ansible.builtin.yum:
      name: 
        - scap-security-guide
        - openscap-scanner
        - openscap
        - insights-client
      state: present
  
  - name: Register the insights client
    redhat.insights.insights_register:
      state: present
